/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peminjaman_peralatan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author sekonol
 */
public class Kerusakan extends javax.swing.JFrame {

    /**
     * Creates new form Kerusakan
     */
    private String statusAK;
    public Kerusakan() {
        initComponents();
        aktif();
        tanggal();
        id_alat_kerja.setVisible(false);
        LoadPinjam();
        lebarKolomx();
        no_kerusakan1.setEnabled(false);
        stat.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bsimpan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bupdate1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        no_kerusakan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tgl_selesai_perbaikan = new javax.swing.JTextField();
        nama_alat = new javax.swing.JComboBox<>();
        id_alat_kerja = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nama_kerusakan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelx = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        no_kerusakan1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bsimpan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INPUT KERUSAKAN ALAT KERJA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(tambah))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        bupdate1.setText("KELUAR FORM");
        bupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 102));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nomor Kerusakan");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Alat");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Kerusakan");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal");

        tgl_selesai_perbaikan.setText("-");

        nama_alat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nama_alatItemStateChanged(evt);
            }
        });
        nama_alat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_alatActionPerformed(evt);
            }
        });

        status.setText("PROSES");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal Perbaikan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(id_alat_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(no_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addGap(26, 26, 26)
                            .addComponent(tanggal))
                        .addComponent(nama_kerusakan)
                        .addComponent(nama_alat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tgl_selesai_perbaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(no_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_alat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_alat_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nama_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tgl_selesai_perbaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 102));

        tabelx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelx.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelx);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("DATA ALAT YANG MASIH PROSES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(30, 30, 30))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("INPUT KERUSAKAN ALAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Nomor Kerusakan");

        stat.setText("CLOSED");

        jLabel10.setText("Status");

        bsimpan1.setText("UPDATE PROSES");
        bsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no_kerusakan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bsimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_kerusakan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(bsimpan1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void tampil_alat() {
        try {
            Koneksi conn = new Koneksi();
            Statement stat = conn.buatkoneksi().createStatement();
            String sql = "Select * from alat_kerja";
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                nama_alat.addItem(res.getString("nama_alat"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan.." + e);
        }
    }

    //method menampilkan nim ke textbox txnim
    public void tampil_kode_alat() {
        String sql = "SELECT * FROM alat_kerja WHERE nama_alat = '" + nama_alat.getSelectedItem() + "'";
        try {

            Koneksi conn = new Koneksi();
            try (Statement stat = conn.buatkoneksi().createStatement()) {
                ResultSet res = stat.executeQuery(sql);
                if (res.next()) {
                    String isi_nim = res.getString("id_alat_kerja");
                    id_alat_kerja.setText(isi_nim);
                }
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null,"Terjadi Kesalahan.."+e);
        }
    }

    public void daftarData() {
        try {
            Koneksi con = new Koneksi();
            try (Statement stat = con.buatkoneksi().createStatement()) {
                ResultSet rs = stat.executeQuery(sqlcreate);
                tableModel.setRowCount(0);
                while (rs.next()) {
                    String id = rs.getString("no_kerusakan"); //'id_alat_kerja' sesuai field di DB
                    String nik = rs.getString("tanggal"); //'id_alat_kerja' sesuai field di DB
                    String nama = rs.getString("nama_alat"); //'nama_alat' sesuai field di DB
                    String ket = rs.getString("nama_kerusakan"); //'jenis' sesuai field di DB
                    String tgl = rs.getString("tgl_selesai_perbaikan"); //'jenis' sesuai field di DB
                    String status = rs.getString("status"); //'jenis' sesuai field di DB
                    String[] data = {id, nik, nama, ket, tgl, status};
                    tableModel.addRow(data);
                }
            }
        } catch (SQLException sq) {
            JOptionPane.showMessageDialog(rootPane, "SQL Error");
        }
    }
    DefaultTableModel tableModel;
    String sqlcreate;

    public void daftarDatax() {
        try {
            Koneksi con = new Koneksi();
            Statement stat = con.buatkoneksi().createStatement();
            ResultSet rs = stat.executeQuery(sqlcreate);
            tableModel.setRowCount(0);
            while (rs.next()) {
                String ID = rs.getString("no_kerusakan");
                String nm_part = rs.getString("tanggal");
                String har = rs.getString("nama_alat");
                String qt = rs.getString("nama_kerusakan");
                String tot = rs.getString("status");
                String[] data = {ID, nm_part, har, qt, tot};
                tableModel.addRow(data);
            }
            stat.close();
        } catch (SQLException sq) {
            JOptionPane.showMessageDialog(rootPane, "SQL Error");
        }
    }

    //Prosdeur yang diperlukan
    public void aktif() {
        no_kerusakan.setEnabled(false);
        nama_alat.setEnabled(false);
        nama_kerusakan.setEnabled(false);
        tanggal.setEnabled(false);
        tgl_selesai_perbaikan.setEnabled(false);
        status.setEnabled(false);
        bsimpan.setEnabled(false);

    }

    public void nonaktif() {
        no_kerusakan.setEnabled(false);
        nama_alat.setEnabled(true);
        nama_kerusakan.setEnabled(true);
        tanggal.setEnabled(false);
        tgl_selesai_perbaikan.setEnabled(true);
        status.setEnabled(true);
        bsimpan.setEnabled(true);
    }

    public void tampil_ID_Service() {
        try {
            Koneksi conn = new Koneksi();
            Statement stat = conn.buatkoneksi().createStatement();
            String sql = "Select MAX(right(no_kerusakan,3)) as no from kerusakan";
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                if (res.first() == false) {
                    no_kerusakan.setText("KR0001");

                } else {
                    res.last();
                    int auto_id = res.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int noLong = no.length();
                    //MENGATUR jumlah 0
                    for (int a = 0; a < 3 - noLong; a++) {
                        no = "0" + no;
                    }
                    no_kerusakan.setText("KR0" + no);

                }
            }
            res.close();
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                    "Kesalahan", JOptionPane.WARNING_MESSAGE);

        }
    }

    public void tanggal() {
        java.util.Date Tanggal = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        tanggal.setText(kal.format(Tanggal));
    }

    public void lebarKolom() {
        TableColumn column;
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabel.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tabel.getColumnModel().getColumn(1);
        column.setPreferredWidth(90);
        column = tabel.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = tabel.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        column = tabel.getColumnModel().getColumn(4);
        column.setPreferredWidth(100);
        column = tabel.getColumnModel().getColumn(5);
        column.setPreferredWidth(80);
    }

    public void lebarKolomx() {
        TableColumn column;
        tabelx.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabelx.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tabelx.getColumnModel().getColumn(1);
        column.setPreferredWidth(90);
        column = tabelx.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = tabelx.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        column = tabelx.getColumnModel().getColumn(4);
        column.setPreferredWidth(80);
    }

    public void updateStatus() {
        try {
            String sql = "update kerusakan set tgl_selesai_perbaikan='" + tgl_selesai_perbaikan.getText() + "',status='" + status.getText() + "' where no_kerusakan='" + no_kerusakan.getText() + "'";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {

                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data sudah di update");
                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Update data gagal...");
                }
            }
            daftarData();
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }

    }

    public void LoadPinjam() {
        Object row[] = {"No. Kerusakan", "Tanggal", "Nama Alat", "Nama Kerusakan", "Status"};
        tableModel = new DefaultTableModel(null, row);
        tabelx.setModel(tableModel);
        sqlcreate = "SELECT * FROM _kerusakan where status = 'PROSES'";
        daftarDatax();
    }

    public void updateStatusRS() {
        try {
            String sql = "UPDATE alat_kerja SET status='rusak' WHERE nama_alat= '" + nama_alat.getSelectedItem() + "'";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                stat.executeUpdate();
            }
        } catch (SQLException se) {
        }
    }

    public void updateStatusBN() {
        try {
            String sql = "UPDATE alat_kerja SET status='Tersedia' WHERE nama_alat= '" +statusAK+ "'";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                stat.executeUpdate();
            }
        } catch (SQLException se) {
        }
    }

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        try {
            String sql = "insert into kerusakan" + "(no_kerusakan,tanggal,id_alat_kerja,nama_kerusakan,tgl_selesai_perbaikan,status) values(?,?,?,?,?,?)";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {
                    stat.setString(1, no_kerusakan.getText());           //mengisi textfield id
                    stat.setString(2, tanggal.getText());
                    stat.setString(3, id_alat_kerja.getText());
                    stat.setString(4, nama_kerusakan.getText());
                    stat.setString(5, tgl_selesai_perbaikan.getText());//mengisi textfield nama_konsumen
                    stat.setString(6, status.getText());

                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data sudah tersimpan");

                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Kode Kerusakan ini sudah ada dalam database");
                }
            }
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }
        updateStatusRS();
        aktif();
        LoadPinjam();
        lebarKolomx();

    }//GEN-LAST:event_bsimpanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        nonaktif();
        tampil_alat();
        tampil_ID_Service();
        tgl_selesai_perbaikan.setEnabled(false);
        status.setEnabled(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void bupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate1ActionPerformed
        dispose();
    }//GEN-LAST:event_bupdate1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void nama_alatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nama_alatItemStateChanged
        tampil_kode_alat();
    }//GEN-LAST:event_nama_alatItemStateChanged

    private void nama_alatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_alatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_alatActionPerformed

    private void tabelxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelxMouseClicked
        try {
            int row = tabelx.rowAtPoint(evt.getPoint());

            String ID = tabelx.getValueAt(row, 0).toString();

            no_kerusakan1.setText(String.valueOf(ID));
            statusAK = tabelx.getValueAt(row, 2).toString();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_tabelxMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Object row[] = {"No. Kerusakan", "Tanggal", "Nama Alat", "Nama Kerusakan", "Tgl. Selesai", "Status"};
        tableModel = new DefaultTableModel(null, row);
        tabel.setModel(tableModel);
        sqlcreate = "SELECT * FROM _kerusakan where status = 'CLOSED'";
        daftarData();
        lebarKolom();
    }//GEN-LAST:event_formWindowActivated

    private void bsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpan1ActionPerformed
        try {
            String sql = "update kerusakan set tgl_selesai_perbaikan= '" + tanggal.getText() + "', status='" + stat.getText() + "' where no_kerusakan='" + no_kerusakan1.getText() + "'";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {

                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data sudah di update");
                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Pilih dahulu data untuk di Closing");
                }
            }
            daftarData();
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }
        updateStatusBN();
        aktif();
        LoadPinjam();
        lebarKolomx();
    }//GEN-LAST:event_bsimpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kerusakan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bsimpan1;
    private javax.swing.JButton bupdate1;
    private javax.swing.JTextField id_alat_kerja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> nama_alat;
    private javax.swing.JTextField nama_kerusakan;
    private javax.swing.JTextField no_kerusakan;
    private javax.swing.JTextField no_kerusakan1;
    private javax.swing.JTextField stat;
    private javax.swing.JTextField status;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabelx;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tgl_selesai_perbaikan;
    // End of variables declaration//GEN-END:variables
}
