/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peminjaman_peralatan;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author sekonol
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNoAlat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtNamaAlat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStatus = new javax.swing.JTable();
        cbShift = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        bupdate1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PEMINJAMAN DAN PENGEMBALIAN ALAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nomor Alat");

        txtNoAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNoAlatMouseEntered(evt);
            }
        });
        txtNoAlat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoAlatKeyPressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Alat");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIK");

        txtNik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNikMouseEntered(evt);
            }
        });
        txtNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNikKeyPressed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Shift");

        btnCheckIn.setText("CHECK IN");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setText("CHECK OUT");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Alat Tersedia");

        tblStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStatus.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStatusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblStatus);

        cbShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addComponent(txtNoAlat, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNama))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNoAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckOut)
                    .addComponent(btnCheckIn))
                .addContainerGap())
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        bupdate1.setText("KELUAR FORM");
        bupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void aktif() {
        txtNoAlat.setEnabled(true);
        txtNik.setEnabled(true);
    }

    private void nonaktif() {
        txtNoAlat.setEnabled(false);
        txtNik.setEnabled(false);
    }

    public void tanggal() {
        java.util.Date Tanggal = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd/HH:mm:ss");
        txtTanggal.setText(kal.format(Tanggal));
    }

    public void bersih() {
        txtNama.setText("");
        txtNamaAlat.setText("");
        txtNik.setText("");
        txtNoAlat.setText("");

    }

    public void daftarData() {
        try {
            Koneksi con = new Koneksi();
            try (Statement stat = con.buatkoneksi().createStatement()) {
                ResultSet rs = stat.executeQuery(sqlcreate);
                tableModel.setRowCount(0);
                while (rs.next()) {
                    String id = rs.getString("id_trx");
                    String nik = rs.getString("nik");
                    String nama = rs.getString("nama_karyawan");
                    String ket = rs.getString("nama_dept");
                    String tgl = rs.getString("tanggal");
                    String shift = rs.getString("shift");
                    String alat = rs.getString("nama_alat");
                    String status = rs.getString("trx");
                    String[] data = {id, nik, nama, ket, tgl, shift, alat, status};
                    tableModel.addRow(data);
                }
            }
        } catch (SQLException sq) {
            JOptionPane.showMessageDialog(rootPane, "SQL Error" + sq);
        }
    }

    DefaultTableModel tableModel;
    String sqlcreate;

    public void lebarKolom() {
        TableColumn column;
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabel.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column = tabel.getColumnModel().getColumn(1);
        column.setPreferredWidth(90);
        column = tabel.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = tabel.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        column = tabel.getColumnModel().getColumn(4);
        column.setPreferredWidth(90);
        column = tabel.getColumnModel().getColumn(5);
        column.setPreferredWidth(70);
        column = tabel.getColumnModel().getColumn(6);
        column.setPreferredWidth(150);
        column = tabel.getColumnModel().getColumn(7);
        column.setPreferredWidth(100);
    }

    public void daftarDataStatus() {
        try {
            Koneksi con = new Koneksi();
            try (Statement stat = con.buatkoneksi().createStatement()) {
                ResultSet rs = stat.executeQuery(sqlcreate);
                tableModel.setRowCount(0);
                while (rs.next()) {
                    String jenis = rs.getString("jenis");
                    String jumlah = rs.getString("Jumlah");
                    String[] data = {jenis, jumlah};
                    tableModel.addRow(data);
                }
            }
        } catch (SQLException sq) {
            JOptionPane.showMessageDialog(rootPane, "SQL Error" + sq);
        }
    }

    public void lebarKolomStatus() {
        TableColumn column;
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabel.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column = tabel.getColumnModel().getColumn(1);
        column.setPreferredWidth(100);
    }

    private void tampil_id() {
        try {
            Koneksi conn = new Koneksi();
            Statement stat = conn.buatkoneksi().createStatement();
            String sql = "SELECT * FROM alat_kerja WHERE id_alat_kerja = '" + txtNoAlat.getText() + "'";
            ResultSet res = stat.executeQuery(sql);

            if (res.next()) {

                String is_no_alat = res.getString("id_alat_kerja");
                String is_nama_alat = res.getString("nama_alat");
                String status = res.getString("status");

                if (!status.equalsIgnoreCase("tersedia")) {
                    JOptionPane.showMessageDialog(null, "Alat dengan ID ini sudah dipinjam silahkan CHECKOUT Terlebih dahulu");
                    tampil_alat_by_id();
                    btnCheckIn.setEnabled(false);
                    btnCheckOut.setEnabled(true);
                } else {
                    bersih();
                    txtNoAlat.setText(is_no_alat);
                    txtNamaAlat.setText(is_nama_alat);
                    btnCheckIn.setEnabled(true);
                    btnCheckOut.setEnabled(false);
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Salah.." + e);
        }
        txtNamaAlat.setEnabled(false);
    }

    private void tampil_alat_by_id() {
        try {
            Koneksi conn = new Koneksi();
            Statement stat = conn.buatkoneksi().createStatement();
            String sql = "SELECT t.id_trx, t.id_alat_kerja, a.nama_alat, a.status, t.tanggal, t.nik, t.shift,k.nama_karyawan FROM alat_kerja a,transaksi t, karyawan k "
                    + "WHERE a.id_alat_kerja = t.id_alat_kerja AND t.nik = k.nik AND a.id_alat_kerja = '" + txtNoAlat.getText() + "' ORDER BY t.id_trx DESC LIMIT 1";
            ResultSet res = stat.executeQuery(sql);

            if (res.next()) {
                String is_nama_alat = res.getString("nama_alat");
                String is_nama = res.getString("nama_karyawan");
                String is_shift = res.getString("shift");
                String is_nik = res.getString("nik");
                String is_no_alat = res.getString("id_alat_kerja");

                String status = res.getString("status");

                if (!status.equalsIgnoreCase("tersedia")) {
                    txtNama.setText(is_nama);
                    txtNamaAlat.setText(is_nama_alat);
                    txtNik.setText(is_nik);
                    txtNoAlat.setText(is_no_alat);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Salah.." + e);
        }
        txtNamaAlat.setEnabled(false);
    }

    private void tampil_nama() {
        try {
            Koneksi conn = new Koneksi();
            Statement stat = conn.buatkoneksi().createStatement();
            String sql = "SELECT * FROM karyawan WHERE nik = '" + txtNik.getText() + "'";
            ResultSet res = stat.executeQuery(sql);

            if (res.next()) {
                String is_nama = res.getString("nama_karyawan");
                txtNama.setText(is_nama);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Salah.." + e);
        }
        txtNama.setEnabled(false);
    }

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed

        insertTransaksiIn();
        updateStatusIn();
        bersih();
        aktif();
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void insertTransaksiIn() {
        try {
            String sql = "insert into transaksi " + "(tanggal,id_alat_kerja,nik,shift,trx) values(?,?,?,?,?);";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {

                    stat.setString(1, txtTanggal.getText());
                    stat.setString(2, txtNoAlat.getText());
                    stat.setString(3, txtNik.getText());
                    stat.setString(4, (String) cbShift.getSelectedItem());
                    stat.setString(5, "peminjaman");

                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Alat " + txtNoAlat.getText() + "Dipinjam");

                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Gagal " + se);
                }
            }
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }

    }

    private void updateStatusIn() {
        try {
            String sql = "UPDATE alat_kerja SET Status = 'dipinjam' WHERE id_alat_kerja =?";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {

                    stat.setString(1, txtNoAlat.getText());
                    stat.executeUpdate();
                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Gagal" + se);
                }
            }
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }
    }

    private void insertTransaksiOut() {
        try {
            String sql = "insert into transaksi " + "(tanggal,id_alat_kerja,nik,shift,trx) values(?,?,?,?,?);";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {

                    stat.setString(1, txtTanggal.getText());
                    stat.setString(2, txtNoAlat.getText());
                    stat.setString(3, txtNik.getText());
                    stat.setString(4, (String) cbShift.getSelectedItem());
                    stat.setString(5, "pengembalian");

                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Alat " + txtNoAlat.getText() + " sudah dikembalikan");

                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Gagal " + se);
                }
            }
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }

    }

    private void updateStatusOut() {
        try {
            String sql = "UPDATE alat_kerja SET Status = 'Tersedia' WHERE id_alat_kerja =?";
            Koneksi k = new Koneksi();  //membuat objek dengan nama k
            Connection con = k.buatkoneksi();
            try (PreparedStatement stat = con.prepareStatement(sql)) {
                try {

                    stat.setString(1, txtNoAlat.getText());
                    stat.executeUpdate();
                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, "Gagal" + se);
                }
            }
        } catch (SQLException se) {
            System.out.println("Gagal Simpan...");
        }
    }
    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        insertTransaksiOut();
        updateStatusOut();
        bersih();


    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked

    }//GEN-LAST:event_tabelMouseClicked

    private void txtNoAlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNoAlatMouseEntered

    }//GEN-LAST:event_txtNoAlatMouseEntered

    private void txtNikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNikMouseEntered

    }//GEN-LAST:event_txtNikMouseEntered

    private void txtNoAlatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoAlatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampil_id();
        }
    }//GEN-LAST:event_txtNoAlatKeyPressed

    private void txtNikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampil_nama();
        }
    }//GEN-LAST:event_txtNikKeyPressed

    private void bupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate1ActionPerformed
        dispose();
    }//GEN-LAST:event_bupdate1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Object row[] = {"No. Transaksi", "NIK", "Nama Karyawan", "Departemen", "Tgl. Pinjam", "Shift", "Nama Alat", "Transaksi"};
        tableModel = new DefaultTableModel(null, row);
        tabel.setModel(tableModel);
        sqlcreate = "SELECT t.id_trx, k.nik, k.nama_karyawan, d.nama_dept, t.tanggal, t.shift, a.nama_alat, t.trx FROM transaksi t "
                + "JOIN alat_kerja a ON t.id_alat_kerja = a.id_alat_kerja "
                + "JOIN karyawan k ON t.nik = k.nik "
                + "JOIN departemen d ON k.id_dept = d.id_dept ORDER BY t.id_trx DESC LIMIT 10;";
        daftarData();
        lebarKolom();

        Object tbl2[] = {"Jenis", "Jumlah"};
        tableModel = new DefaultTableModel(null, tbl2);
        tblStatus.setModel(tableModel);
        sqlcreate = "SELECT jenis, COUNT(status) AS Jumlah FROM alat_kerja WHERE status = 'Tersedia' GROUP BY jenis;";
        daftarDataStatus();
        lebarKolomStatus();


    }//GEN-LAST:event_formWindowActivated

    private void tblStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStatusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStatusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton bupdate1;
    private javax.swing.JComboBox<String> cbShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tblStatus;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaAlat;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNoAlat;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
